import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import serveStatic from 'serve-static';
import bodyParser from 'body-parser';
import nodemailer from 'nodemailer';
import cors from 'cors';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// Middleware to parse JSON bodies
app.use(bodyParser.json());

// Middleware to enable CORS
app.use(cors());

// Serve static files from the 'dist' directory
app.use(serveStatic(path.join(__dirname, 'dist')));

// Route to handle form submission
app.post('/send-email', async (req, res) => {
  const { name, email, budget, help } = req.body;

  let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: "contact@clearstack.ai",
      pass: "wivy abdo iavj zahq",
    },
  });

  const htmlContent = `
  <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
    <h2 style="background-color: #0075ff; color: white; padding: 15px 20px; border-radius: 10px 10px 0 0; text-align: center; margin: 0;">New Contact Form Submission</h2>
    <div style="padding: 20px; background-color: #f9f9f9; border-radius: 0 0 10px 10px;">
      <p style="font-size: 1.1em; margin-bottom: 10px;"><strong>Name:</strong> ${name}</p>
      <p style="font-size: 1.1em; margin-bottom: 10px;"><strong>Email:</strong> ${email}</p>
      <p style="font-size: 1.1em; margin-bottom: 10px;"><strong>Budget:</strong> ${budget}</p>
      <p style="font-size: 1.1em; margin-bottom: 10px;"><strong>Help:</strong> ${help}</p>
      <hr style="border: 0; height: 1px; background: #ddd; margin: 20px 0;">
      <p style="font-size: 0.9em; color: #666; text-align: center; margin: 0;">This email was automatically generated by ClearStack AI's contact form.</p>
    </div>
  </div>
`;

  try {
    await transporter.sendMail({
      from: '"ClearStack AI Team" <contact@clearstack.ai>',
      to: "contact@clearstack.ai, collin@clearstack.ai, stefanos@clearstack.ai, justice@clearstack.ai, stavro@clearstack.ai", // list of receivers
      subject: `New Contact Form Submission from ${name}`, // Subject line
      text: `Name: ${name}\nEmail: ${email}\nBudget: ${budget}\nHelp: ${help}`, // plain text body
      html: htmlContent, // html body
    });
    res.status(200).send({ message: "Email sent successfully!" });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).send({ error: "Error sending email" });
  }
});

// Catch-all route to serve 'index.html'
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

const port = process.env.PORT || 5001;
app.listen(port, () => {
  console.log(`App is listening on port ${port}`);
});
